# Generated by Django 5.2.7 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ultimo_tema_desbloqueado',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
