# Generated by Django 5.2.7 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_userprofile_ultimo_tema_desbloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acepto_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acepto_terminos_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consentimiento_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consentimiento_tutor_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registro_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
